service: biztech-investments
tenant: ianmh
app: biztechapp

frameworkVersion: 3.40.0

plugins:
  - serverless-dynamodb
  - serverless-offline
  - serverless-bundle
  - serverless-domain-manager
  - serverless-prune-plugin
  - serverless-mocha-plugin

provider:
  name: aws
  stage: ${file(../../serverless.common.yml):provider.stage}
  runtime: ${file(../../serverless.common.yml):provider.runtime}
  region: ${file(../../serverless.common.yml):provider.region}
  cfLogs: true
  environment:
    ENVIRONMENT: ${file(../../config.${self:provider.stage}.json):ENVIRONMENT}
    NODE_ENV: ${env:NODE_ENV}
  timeout: 15 # in seconds
  apiGateway:
    restApiId: !ImportValue ${self:provider.stage}-ExtApiGatewayRestApiId
    restApiRootResourceId: !ImportValue ${self:provider.stage}-ExtApiGatewayRestApiRootResourceId
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:us-west-2:432714361962:table/biztechInvestments${self:provider.environment.ENVIRONMENT}"
        - "arn:aws:dynamodb:us-west-2:432714361962:table/biztechTeams${self:provider.environment.ENVIRONMENT}"
        - "arn:aws:dynamodb:us-west-2:432714361962:table/biztechRegistrations${self:provider.environment.ENVIRONMENT}"
        - "arn:aws:dynamodb:us-west-2:432714361962:table/biztechInvestments${self:provider.environment.ENVIRONMENT}/index/team-investments"
        - "arn:aws:dynamodb:us-west-2:432714361962:table/biztechInvestments${self:provider.environment.ENVIRONMENT}/index/investor-investments"

custom: ${file(../../serverless.common.yml):custom}

functions:
  invest:
    handler: handler.invest
    events:
      - http:
          path: investments/invest
          method: post
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: ${cf:biztechApi-${file(../../serverless.common.yml):provider.stage}.CognitoAuthorizer}
  teamStatus:
    handler: handler.teamStatus
    events:
      - http:
          path: investments/teamStatus/{teamId}
          method: get
          request:
            path:
              teamId: true
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: ${cf:biztechApi-${file(../../serverless.common.yml):provider.stage}.CognitoAuthorizer}
  investorStatus:
    handler: handler.investorStatus
    events:
      - http:
          path: investments/investorStatus/{investorId}
          method: get
          request:
            path:
              investorId: true
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: ${cf:biztechApi-${file(../../serverless.common.yml):provider.stage}.CognitoAuthorizer}
  investments:
    handler: handler.investments
    events:
      - http:
          path: investments
          method: get
          cors: true
          authorizer:
            type: COGNITO_USER_POOLS
            authorizerId: ${cf:biztechApi-${file(../../serverless.common.yml):provider.stage}.CognitoAuthorizer}

