service: biztech-quizzes
tenant: ianmh
app: biztechapp

frameworkVersion: 3.40.0

plugins:
  - serverless-dynamodb
  - serverless-offline
  - serverless-bundle
  - serverless-domain-manager
  - serverless-prune-plugin
  - serverless-mocha-plugin

provider:
  name: aws
  stage: ${file(../../serverless.common.yml):provider.stage}
  runtime: ${file(../../serverless.common.yml):provider.runtime}
  region: ${file(../../serverless.common.yml):provider.region}
  cfLogs: true
  environment:
    ENVIRONMENT: ${file(../../config.${self:provider.stage}.json):ENVIRONMENT}
    NODE_ENV: ${env:NODE_ENV}
  timeout: 15 # in seconds
  apiGateway:
    restApiId: !ImportValue ${self:provider.stage}-ExtApiGatewayRestApiId
    restApiRootResourceId: !ImportValue ${self:provider.stage}-ExtApiGatewayRestApiRootResourceId
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "arn:aws:dynamodb:us-west-2:432714361962:table/biztechQuizzes${self:provider.environment.ENVIRONMENT}"
        - "arn:aws:dynamodb:us-west-2:432714361962:table/biztechProfiles${self:provider.environment.ENVIRONMENT}"
    - Effect: Allow
      Action:
        - dynamodb:GetItem
      Resource:
        - "arn:aws:dynamodb:us-west-2:432714361962:table/biztechMembers2026${self:provider.environment.ENVIRONMENT}"

custom: ${file(../../serverless.common.yml):custom}

functions:
  upload:
    handler: handler.upload
    events:
      - http:
          path: quizzes/upload
          method: post
          cors: true

  report:
    handler: handler.report
    events:
      - http:
          path: quizzes/report
          method: get
          cors: true
          authorizer:
             type: COGNITO_USER_POOLS
             authorizerId: ${cf:biztechApi-${file(../../serverless.common.yml):provider.stage}.CognitoAuthorizer}


  all:
    handler: handler.all
    events:
      - http:
          path: quizzes/{event}
          method: get
          request:
            path:
              event: true
          cors: true

  aggregate:
    handler: handler.aggregate
    events:
      - http:
          path: quizzes/aggregate/{event}
          method: get
          request:
            path:
              event: true
          cors: true

  perMbti:
    handler: handler.perMbti
    events:
      - http:
          path: quizzes/perMbti/{mbti}
          method: get
          request:
            path:
              mbti: true
          cors: true

  wrapped:
    handler: handler.wrapped
    events:
      - http:
          path: quizzes/wrapped
          method: post
          cors: true

resources:
  Resources:
    BiztechQuizzes:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: biztechQuizzes${self:provider.environment.ENVIRONMENT}
        BillingMode: PAY_PER_REQUEST
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
          - AttributeName: eventID;year
            AttributeType: S
          - AttributeName: mbti
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
          - AttributeName: eventID;year
            KeyType: RANGE
        GlobalSecondaryIndexes:
          - IndexName: event-query
            KeySchema:
              - AttributeName: eventID;year
                KeyType: HASH
              - AttributeName: id
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
          - IndexName: mbti-query
            KeySchema:
              - AttributeName: mbti
                KeyType: HASH
              - AttributeName: eventID;year
                KeyType: RANGE
            Projection:
              ProjectionType: ALL
